// ===== WALLET DATABASE =====

const wallets = {

  USDT: {
    TRC20: "YOUR_TRC20_WALLET_ADDRESS",
    ERC20: "YOUR_ERC20_WALLET_ADDRESS",
    BEP20: "YOUR_BEP20_WALLET_ADDRESS",
    SOLANA: "YOUR_SOLANA_USDT_ADDRESS"
  },

  BTC: {
    BTC: "YOUR_BITCOIN_ADDRESS"
  },

  ETH: {
    ERC20: "YOUR_ETHEREUM_ADDRESS"
  },

  SOL: {
    SOLANA: "YOUR_SOLANA_ADDRESS"
  },

  LTC: {
    LTC: "YOUR_LITECOIN_ADDRESS"
  }

};

module.exports = wallets;